resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

client_script 'client.lua'
-- server_script 'server.lua'

ui_page 'html/index.html'

files {
    'html/index.html',
    'html/styles.css',
    'html/main.js',
    'html/weapons/AdvancedRifle.png',
    'html/weapons/APPistol.png',
    'html/weapons/AssaultRifle.png',
    'html/weapons/AssaultShotgun.png',
    'html/weapons/AssaultSMG.png',
    'html/weapons/Autoshotgun.png',
    'html/weapons/BullpupRifle.png',
    'html/weapons/BullpupShotgun.png',
    'html/weapons/BZGas.png',
    'html/weapons/CarbineRifle.png',
    'html/weapons/CombatMG.png',
    'html/weapons/CombatPistol.png',
    'html/weapons/Compactlouncher.png',
    'html/weapons/CompactRifle.png',
    'html/weapons/Doubleaction.png',
    'html/weapons/DoubleBarrelShotgun.png',
    'html/weapons/Firework.png',
    'html/weapons/Flare.png',
    'html/weapons/FlareGun.png',
    'html/weapons/Grenade.png',
    'html/weapons/GrenadeLauncher.png',
    'html/weapons/Gusenberg.png',
    'html/weapons/HeavyPistol.png',
    'html/weapons/HeavyShotgun.png',
    'html/weapons/HeavySniper.png',
    'html/weapons/HomingLauncher.png',
    'html/weapons/MachinePistol.png',
    'html/weapons/MarksmanPisto.png',
    'html/weapons/MarksmanRifle.png',
    'html/weapons/MG.png',
    'html/weapons/MicroSMG.png',
    'html/weapons/Minigun.png',
    'html/weapons/minismg.png',
    'html/weapons/Molotov.png',
    'html/weapons/Musket.png',
    'html/weapons/PDW.png',
    'html/weapons/pistol.png',
    'html/weapons/Pistol50.png',
    'html/weapons/PumpShotgun.png',
    'html/weapons/Railgun.png',
    'html/weapons/Raycarbine.png',
    'html/weapons/rayminigun.png',
    'html/weapons/Raypistol.png',
    'html/weapons/Revolver.png',
    'html/weapons/RPG.png',
    'html/weapons/SawnoffShotgun.png',
    'html/weapons/SMG.png',
    'html/weapons/SmokeGrenade.png',
    'html/weapons/SniperRifle.png',
    'html/weapons/SNSPistol.png',
    'html/weapons/SpecialCarbine.png',
    'html/weapons/StunGun.png',
    'html/weapons/VintagePistol.png',
}